name: 'Github Actions for Ansible Playbooks'
description: 'Github Actions for Ansible Playbooks'
inputs:
  playbook:
    description: 'Path to the Ansible playbook'
    required: true
    default: 'playbooks/main.yaml'
  inventory:
    description: 'Path to the inventory file'
    required: false
    default: '/opt/yacht/inventory'
runs:
  using: 'docker'
  image: 'Dockerfile'
