name: 'Github Actions for Ansible Playbooks'
description: 'Github Actions for Ansible Playbooks'
inputs:
  playbook:
    description: 'Path to the Ansible playbook'
    required: true
    default: 'playbooks/main.yaml'
  inventory:
    description: 'Path to the inventory file'
    required: false
    default: '/opt/yacht/inventory'
  vault_pass:
    description: 'Vault password'
    required: false
  vault:
    description: 'Vault file content'
    required: false
  args:
    description: 'arguments passed to ansible playbook'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
